name: ra2ce_examples_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.13
  - conda-forge::folium
  - conda-forge::matplotlib
  - conda-forge::mapclassify
  - pip:
    - git+https://github.com/Deltares/ra2ce.git
    - osmnx==1.7.1
