name: ra2ce_examples_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::gdal=3.5.1
  - conda-forge::fiona
  - conda-forge::poetry=1.3.2
  - pip:
    - git+https://github.com/Deltares/ra2ce.git