name: ra2ce_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.11
  # from here some dragons
  - conda-forge::geopandas
  - conda-forge::rasterio
  - conda-forge::osmnx
  - conda-forge::tqdm
  - conda-forge::geopy
  - conda-forge::momepy
  - conda-forge::rasterstats
  - conda-forge::ipywidgets
  - conda-forge::pyarrow
  # Install poetry 1.3.2 (1.4.*) gives issues.
  # If this does not work then exclude it from the environment and install it manually
  # with: conda install -c conda-forge poetry=1.3.2
  - conda-forge::poetry=1.3.2
  # install jupyterlab and notebook
  - conda-forge::jupyterlab
  - conda-forge::notebook
  # install boto3
  - conda-forge::boto3
  - conda-forge::pandoc