name: ra2ce_graz_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::gdal=3.5.1
  # Install poetry 1.3.2 (1.4.*) gives issues.
  # If this does not work then exclude it from the environment and install it manually
  # with: conda install -c conda-forge poetry=1.3.2
  - conda-forge::poetry=1.3.2
  - conda-forge::pandoc