name: ci-on-push-and-autoformat

on: [push]
jobs:

  CI:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3]
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: github.event_name != 'pull_request'

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          # use the latest mamba version
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          # always activate the ra2ce environment (name is specified in environment.yml)
          environment-file: environment.yml
          auto-activate-base: true
          activate-environment: ra2ce_env

      - name: Install Dependencies
        shell: pwsh
        run: |
          conda activate ra2ce_env
          poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test with pytest
        shell: pwsh
        run: |
          conda activate ra2ce_env
          poetry run pytest -v -m "not slow_test" --cov . --cov-report xml:coverage-reports/coverage-ra2ce.xml --junitxml=xunit-reports/xunit-result-ra2ce.xml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Autoformat code if the check fails
        if: ${{ (matrix.os == 'ubuntu-20.04') && (matrix.python-version == 3.9) }}
        shell: pwsh
        run: |
          conda activate ra2ce_env
          poetry run isort .
          poetry run black .
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout $GITHUB_HEAD_REF
          git commit -am "autoformat: isort & black" && git push || true